available_network:
  - vgg11
  - vgg13
  - vgg16
  - vgg19
  - resnet18
  - resnet34
  - resnet50
  - resnet101
  - resnet152
  - densenet121
  - densenet161
  - densenet169
  - densenet201
  - wide_resnet50
  - wide_resnet101
  - resnext50
  - resnext101
  - mobilenet
  - squeezenet
  - shufflenet_0_5
  - shufflenet_1_0
  - shufflenet_1_5
  - shufflenet_2_0
